#!/bin/sh
#
# Makes a timestamped, commit-stamped archive of the current HEAD,
# or of a particular version if a version is provided.
#
# Assumes versions are tagged with prefix 'v', e.g. 'v1.0.1'.
#
# Author: Todd Gamblin
#
name=rubik

function die {
    echo "$1"
    exit 1
}

if [ -n "$1" ]; then
    label="$1"
    ref="v$1"
    prefix="${name}-${label}"
    if ! git show-ref --tags --quiet --verify -- "refs/tags/$ref"; then
        echo "No such version: $label"
        exit 1
    fi
else
    ref=HEAD
    label=$(git log -1 --format="%ct" HEAD | perl -MPOSIX -le 'print strftime "%F", localtime <STDIN>')
    head=$(git log -1 --format="%h" HEAD)
    prefix="${name}-${label}-${head}"
fi

repo_root=$(git rev-parse --show-toplevel)
tarball=$prefix.tar.gz

if cd $repo_root && git archive --format=tar.gz --prefix="${prefix}/" ${ref} -o "$tarball"; then
    echo "Created $repo_root/$tarball"
else
    die "Failed to create $repo_root/$tarball"
fi

if $(which -s openssl); then
    md5_file="$tarball.md5"
    openssl md5 "$tarball" > "$md5_file"
    echo "Created $md5_file"
else
    die "Could not create md5 hash for $tarball"
fi
